export const meta = {
  name: 'gilbreth-capture',
  description: 'Fetch all 92 Gilbreth HPC doc pages via web-reader swarm, write cleaned markdown to content/',
  phases: [{ title: 'Capture', detail: 'one agent per Gilbreth doc page (fetch -> clean -> write)' }],
}

const BASE = '/home/ubuntu/Documents/GitHub/gilberth-skill'
const PREFIX = 'https://docs.rcac.purdue.edu/userguides/gilbreth/'

// URL list embedded directly (avoids args-serialization issues).
const urls = [
  "https://docs.rcac.purdue.edu/userguides/gilbreth/accounts/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/biography/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/compile_gpu/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/compile_hybrid/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/compile_intel_mkl/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/compile_mpi/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/compile_openmp/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/compile/compile_serial/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/faqs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/cluster_tools/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/files/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/interactive/desktop/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/interactive/matlab/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/interactive/notebook/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/interactive/rstudio/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/interactive_apps/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/gateway/jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/overview/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/ansysfluent/calculating/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/ansysfluent/preparing_cases/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/ansysfluent/submit_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/ansysfluent/tui_journal/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/ansysfluent_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/apptainer_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/cancelling_job/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/checking_output/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/creating_the_submission_script/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/directives/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/example_installing_r_packages/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/example_loading_into_r/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/example_python_job/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/example_r_profile_setup/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/example_rstudio/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/example_running_r_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/python_conda/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/python_env_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/python_numpy/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/python_packages/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/python_pip/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/examples/python_source/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/gaussian_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/generic_slurm_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/gpu_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/gpu_usage_monitoring/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/holding_job/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/interactive_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/job_dependencies/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/learning/customml/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/learning/ml_batch/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab/implicit_parallelism/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab/interpreter/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab/mdcs_parallel/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab/parfor/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab/profile_manager/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab/spmd/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/matlab_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/monitoring_job/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/monitoring_resources/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/mpi_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/multiple_node/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/openmp_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/python_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/queues/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/r_example/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/serial_jobs/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/simple_job/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/run_jobs/submit_script/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/software/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/archive_and_compression/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/environment_variables/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/ftp_sftp/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/globus/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/home_directory/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/hsi/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/htar/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/long_term_storage/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/recover/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/recover/flost/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/recover/mac/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/recover/manual/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/recover/windows/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/scp/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/scratch_space/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/sharing/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/storage_quota/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/tmp_directory/",
  "https://docs.rcac.purdue.edu/userguides/gilbreth/storage/windows_network_drive/",
]

const SUMMARY_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    status: { type: 'string', enum: ['OK', 'FAIL'] },
    rel: { type: 'string' },
    title: { type: 'string' },
    word_count: { type: 'integer' },
    topics: { type: 'string', description: '3-6 comma-separated key topics' },
    reason: { type: 'string', description: 'failure reason, only when status=FAIL' },
  },
  required: ['status', 'rel', 'word_count', 'topics'],
}

function promptFor(url) {
  const rel = url.slice(PREFIX.length).replace(/\/$/, '')
  const section = rel.split('/')[0]
  const outPath = BASE + '/content/' + rel + '.md'
  return [
    'You capture ONE documentation page into a knowledge base. Do exactly the steps below.',
    '',
    'SOURCE URL: ' + url,
    'WRITE TO (absolute): ' + outPath,
    'SECTION: ' + section,
    '',
    'STEP 1 — FETCH. Call the MCP tool named `mcp__web-reader__webReader` with exactly:',
    '  url: "' + url + '"',
    '  return_format: "markdown"',
    '  retain_images: false',
    'The tool returns a JSON object string with fields title, description, url, content.',
    'Parse it and take the value of the `content` field — that is the article body in markdown.',
    '',
    'STEP 2 — CLEAN the article body. Remove ALL of these if present (they are site chrome, not content):',
    '  - the global navigation / sidebar table of contents (long lists of other clusters/pages)',
    '  - breadcrumbs, "Edit on ...", "Was this page helpful?", share/print buttons',
    '  - the trailing line "__Back to Gilbreth User Guide__" / "Back to ..." footer links',
    '  - the "Important: Use Microsoft Authenticator ..." site banner unless the page itself is about login',
    'KEEP everything substantive: every heading, paragraph, table (render tables as markdown tables),',
    'bullet/numbered list, and ESPECIALLY every fenced code block (```bash, ```python, etc.) — reproduce',
    'them verbatim, including every `#SBATCH ...` line, every `module load ...`, every command. These are',
    'the most important part. Do NOT summarize code or commands — keep them exact and complete.',
    '',
    'STEP 3 — PREPEND a YAML metadata header, then a blank line, then the cleaned body:',
    '---',
    'source: ' + url,
    'section: ' + section,
    'slug: ' + rel,
    'title: <the page H1 / title from the fetched content>',
    '---',
    '',
    'STEP 4 — WRITE. Use the Write tool to write the full result (header + blank line + body) to exactly:',
    '  ' + outPath,
    'If the path has subdirectories they will be created automatically.',
    '',
    'STEP 5 — REPORT via the structured schema. Set status="OK" if a file was written with real content,',
    'word_count = approximate words in the written body, title = the page title, topics = 3-6 key topics.',
    'If the fetch genuinely failed after the call (error returned, or content came back empty), set',
    'status="FAIL" with a short reason and word_count=0. Do not return prose; the schema is your return value.',
  ].join('\n')
}

phase('Capture')
log('Capturing ' + urls.length + ' Gilbreth pages, one agent each...')
const summaries = await parallel(urls.map(u => () =>
  agent(promptFor(u), { label: u.slice(PREFIX.length).replace(/\/$/, ''), phase: 'Capture', schema: SUMMARY_SCHEMA })
))

const clean = summaries.filter(Boolean)
const ok = clean.filter(s => s.status === 'OK')
const fail = clean.filter(s => s.status === 'FAIL')
const totalWords = ok.reduce((a, s) => a + (s.word_count || 0), 0)
log('Done: ' + ok.length + ' OK, ' + fail.length + ' FAIL, ~' + totalWords + ' words captured')
return {
  total: urls.length,
  ok: ok.length,
  failed: fail.length,
  total_words: totalWords,
  failures: fail,
  captured: ok.map(s => ({ rel: s.rel, title: s.title, words: s.word_count, topics: s.topics })),
}
